{
 "title": "Monitoramento da Aplicação",
 "tags": [ "observabilidade" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Aplicação no ar (up)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"app\"}"
    }
   ]
  },
  {
   "title": "Requisições por segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "targets": [
    { "expr": "rate(app_requests_total[1m])", "legendFormat": "{{endpoint}} ({{http_status}})" }
   ]
  },
  {
   "title": "Latência (p95) em segundos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(app_request_latency_seconds_bucket[5m]))",
     "legendFormat": "p95"
    }
   ]
  }
 ]
}